spring:
  application:
    name: customerapi

  datasource:
    url: jdbc:postgresql://localhost:5432/niitcustomerdb
    username: postgres
    password: admin
    initialize: false
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: default
    show-sql: true

server:
  port: 7074