server:
  port: 8080

spring:
  application:
    name: customer-service

order:
  service:
    url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

#  datasource:
#    url: jdbc:mysql://localhost:3306/customerdb?createDatabaseIfNotExist=true
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
