server:
  port: 9000

spring:
  application:
    name: customer

  datasource:
    url: jdbc:mysql://localhost:3306/customerdb?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
