#version: '3.8'
services:
  vault:
    image: vault:1.2.2
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: "server -dev"

networks:
  default:
    external:
      name: niitnetwork