server:
  port: 8081
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
spring:
  application:
    name: fraud
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://localhost:3306/ms-db-fraud
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
#  zipkin:
#    base-url: http://localhost:9411
#  rabbitmq:
#    addresses: localhost:5672
#  profiles:
#    active: default
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true
#    enabled: true

